export {
  registerRequestSchema,
  loginRequestSchema,
  type RegisterRequestInput,
  type LoginRequestInput,
} from './auth';

export {
  createAthleteSchema,
  updateIdentitySchema,
  setSportSchema,
  setPositionsSchema,
  physicalSchema,
  academicSchema,
  recruitingSchema,
  visibilitySchema,
  biographySchema,
  schoolTeamSchema,
  guardianInviteSchema,
  advanceOnboardingSchema,
  type CreateAthleteInput,
  type UpdateIdentityInput,
  type SetSportInput,
  type SetPositionsInput,
  type PhysicalInput,
  type AcademicInput,
  type RecruitingInput,
  type VisibilityInput,
  type BiographyInput,
  type SchoolTeamInput,
  type GuardianInviteInput,
  type AdvanceOnboardingInput,
} from './athlete';

export {
  createSeasonSchema,
  createAthleteSeasonSchema,
  updateAthleteSeasonSchema,
  createGameSchema,
  updateGameSchema,
  upsertParticipationSchema,
  upsertGameStatisticsSchema,
  createPerformanceResultSchema,
  type CreateSeasonInput,
  type CreateAthleteSeasonInput,
  type UpdateAthleteSeasonInput,
  type CreateGameInput,
  type UpdateGameInput,
  type UpsertParticipationInput,
  type UpsertGameStatisticsInput,
  type CreatePerformanceResultInput,
} from './performance';
