export {
  hasRole,
  isScoutAiAdmin,
  assertAuthenticated,
  canViewAdminSystemInfo,
  canCreateOwnAthleteProfile,
  canEditOwnAthleteProfile,
  canViewAthleteOwnerData,
  canViewPublicAthleteProfile,
  canManageGuardianLink,
  canPublishAthleteProfile,
  canManageOwnCompetitionData,
  canSetVerificationStatus,
  type AuthorizationSubject,
  type AuthorizationResult,
  type PublicAthleteViewContext,
} from './policies';
